version: '2'
services:
  lt.pokedex:
    build: .
    volumes:
      - ./:/usr/src/lt.pokedex
      - /usr/src/lt.pokedex/node_modules
      - /usr/src/lt.pokedex/pokeapi
      - /usr/src/lt.pokedex/data
  test:
    extends:
      service: lt.pokedex
    command: yarn test -- --watch
