const db = require('../db')()
const get = require('./get')

module.exports = {
  ability: get('ability')(db),
  berry: get('berry')(db),
  berryFirmness: get('berryFirmness')(db),
  berryFlavor: get('berryFlavor')(db),
  characteristic: get('characteristic')(db),
  contestEffect: get('contestEffect')(db),
  contestType: get('contestType')(db),
  eggGroup: get('eggGroup')(db),
  encounterCondition: get('encounterCondition')(db),
  encounterConditionValue: get('encounterConditionValue')(db),
  encounterMethod: get('encounterMethod')(db),
  evolutionChain: get('evolutionChain')(db),
  evolutionTrigger: get('evolutionTrigger')(db),
  gender: get('gender')(db),
  generation: get('generation')(db),
  growthRate: get('growthRate')(db),
  item: get('item')(db),
  itemAttribute: get('itemAttribute')(db),
  itemCategory: get('itemCategory')(db),
  itemFlingEffect: get('itemFlingEffect')(db),
  itemPocket: get('itemPocket')(db),
  language: get('language')(db),
  location: get('location')(db),
  locationArea: get('locationArea')(db),
  machine: get('machine')(db),
  move: get('move')(db),
  moveAilment: get('moveAilment')(db),
  moveBattleStyle: get('moveBattleStyle')(db),
  moveCategory: get('moveCategory')(db),
  moveDamageClass: get('moveDamageClass')(db),
  moveLearnMethod: get('moveLearnMethod')(db),
  moveTarget: get('moveTarget')(db),
  nature: get('nature')(db),
  palParkArea: get('palParkArea')(db),
  pokeathlonStat: get('pokeathlonStat')(db),
  pokedex: get('pokedex')(db),
  pokemon: get('pokemon')(db),
  pokemonColor: get('pokemonColor')(db),
  pokemonForm: get('pokemonForm')(db),
  pokemonHabitat: get('pokemonHabitat')(db),
  pokemonShape: get('pokemonShape')(db),
  pokemonSpecies: get('pokemonSpecies')(db),
  region: get('region')(db),
  stat: get('stat')(db),
  superContestEffect: get('superContestEffect')(db),
  type: get('type')(db),
  version: get('version')(db),
  versionGroup: get('versionGroup')(db)
}
